version: 2
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
python:
  version: 3
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - cg
