[build-system]
requires = [
    "setuptools>=61.0.0",
    "oldest-supported-numpy"
]
build-backend = "setuptools.build_meta"

[project]
name = "adrt"
description = "Fast approximate discrete Radon transform for NumPy arrays"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "BSD-3-Clause"}
authors = [
  {name = "Karl Otness"},
  {name = "Donsub Rim"}
]
dependencies = [
  "numpy>=1.17,<2"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: BSD License",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: C++",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS"
]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/karlotness/adrt"
documentation = "https://adrt.readthedocs.io"
repository = "https://github.com/karlotness/adrt"
issues = "https://github.com/karlotness/adrt/issues"

# Additional setuptools settings
[tool.setuptools]
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "adrt.__version__"}

# cibuildwheel settings
[tool.cibuildwheel]
build = "cp38-*"
skip = ["*-musllinux*", "pp*"]
build-frontend = "build"
before-test = "pip install -r {package}/tests/test_requirements.txt"
test-command = "pytest {package}/tests"
test-skip = "*-macosx_universal2:arm64"

# Specify manylinux image versions
manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.linux]
archs = ["auto64"]

[tool.cibuildwheel.linux.environment]
CFLAGS = "-O3 -g0 -flto -fvisibility=hidden -fvisibility-inlines-hidden -fno-plt -fcf-protection=full -fstack-protector-strong -fstack-clash-protection -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Wsign-compare -Wfloat-conversion -Warith-conversion -Wstrict-overflow=5 -Wfloat-equal -Wimplicit-fallthrough -Warray-bounds=2 -Wvla -Wunused-result -Wduplicated-branches -Wduplicated-cond -Wnull-dereference -Wstack-protector -Wtrampolines -Walloca -Wshift-overflow=2 -Wswitch-default -Wshadow -Wundef -Wcast-align=strict -Wstringop-overflow=4 -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -Wformat-signedness -D_FORTIFY_SOURCE=2 -DNDEBUG"
LDFLAGS = "-Wl,--strip-all,--as-needed,--sort-common,-O1,-z,relro,-z,now,-z,noexecstack"

[tool.cibuildwheel.macos]
archs = ["universal2"]

[tool.cibuildwheel.macos.environment]
CFLAGS = "-O3 -g0 -flto -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wpedantic -Wconversion -Wfloat-equal -Wimplicit-fallthrough -DNDEBUG"
LDFLAGS = "-Wl,-S,-x,-dead_strip_dylibs"

[tool.cibuildwheel.windows]
archs = ["auto"]

[tool.cibuildwheel.windows.environment]
CL = "/permissive- /Zc:inline,preprocessor,__cplusplus /DNDEBUG"
