name: "Release"
on:
  push:
    tags:
      - 'v[0-9]*'
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v3
      id: setup-python
      with:
        python-version: '3.10'
    - name: Cache pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-releasecheck-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: |
          pip-releasecheck-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
          pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox
    - name: Check version strings
      run: python -m tox -e checkver -- --tag_ref '${{ github.ref }}'
    - name: Run tox tests
      run: python -m tox -e py
      env:
        CFLAGS: '-O3 -g0 -flto -fvisibility=hidden -fvisibility-inlines-hidden -UNDEBUG -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC'
    - name: Clean up
      run: python -m pip cache remove adrt || true
  check-cpp:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v3
      id: setup-python
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: cache-catch2/
        key: cache2-f5adf6a4c323792
    - name: Download dependencies
      run: python tools/download_catch2.py tests/cpp/catch2/catch.hpp --cache_dir="cache-catch2/"
    - name: Build tests (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: g++ -std=c++11 -g0 -UNDEBUG -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -Wall -Wextra -Wpedantic $(find src/adrt tests/cpp/ -name '*.cpp' -not -name 'adrt_cdefs_py.cpp') -I src/adrt/ -o tests/cpp/test_all.exe
    - name: Build tests (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        $vsinstance=Get-VSSetupInstance | Select-VSSetupInstance -Require Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -Product * -Latest
        & $(Join-Path -Path $vsinstance.InstallationPath -ChildPath Common7\Tools\Launch-VsDevShell.ps1)
        $cppfiles=Get-ChildItem -Path src\adrt\*,tests\cpp\* -Include *.cpp -Exclude adrt_cdefs_py.cpp
        cl /std:c++14 /EHsc /MDd /UNDEBUG /permissive- /Zc:inline,preprocessor,__cplusplus /wd5105 /I src\adrt\ $cppfiles.FullName /link /out:tests\cpp\test_all.exe
    - name: Run tests
      run: ./tests/cpp/test_all.exe
  sdist:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: check-cpp
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
    - name: Build sdist
      run: python -m build --sdist
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/adrt-*.tar.gz
        if-no-files-found: error
    - name: Install test dependencies
      run: python -m pip install --upgrade tox
    - name: Run tox tests
      run: python -m tox -e py --installpkg dist/adrt-*.tar.gz
  wheel:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: check-cpp
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade cibuildwheel
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BEFORE_ALL_WINDOWS: 'pwsh {package}/tools/patch_license_windows.ps1 {package}'
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: wheelhouse/adrt-*.whl
        if-no-files-found: error
    - name: Diagnostics (Linux)
      if: ${{ runner.os == 'Linux' }}
      continue-on-error: true
      run: |
        touch 'diagnostics.txt'
        for wheelfile in wheelhouse/adrt-*.whl; do
          if [[ ! -e "$wheelfile" ]]; then
            continue
          fi
          echo "----- WHEEL: $(basename $wheelfile) -----" | tee -a 'diagnostics.txt'
          dir="$(mktemp -d)"
          unzip -q "$wheelfile" -d "$dir"
          readelf --wide --symbols --dynamic "${dir}"/adrt/*.so | tee -a 'diagnostics.txt'
          echo | tee -a 'diagnostics.txt'
        done
    - name: Diagnostics (Windows)
      if: ${{ runner.os == 'Windows' }}
      continue-on-error: true
      run: |
        $vsinstance=Get-VSSetupInstance | Select-VSSetupInstance -Require Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -Product * -Latest
        & $(Join-Path -Path $vsinstance.InstallationPath -ChildPath Common7\Tools\Launch-VsDevShell.ps1)
        $ProgressPreference = 'SilentlyContinue'
        Remove-Item 'wheel-diagnostic' -Recurse -ErrorAction SilentlyContinue
        $baseextract = New-Item -Path . -Name 'wheel-diagnostic' -ItemType 'directory'
        $null = New-Item -Name diagnostics.txt -ItemType File
        Get-ChildItem -Path 'wheelhouse' -Filter 'adrt-*.whl' | ForEach-Object {
          $wheelfile = $_
          Write-Output "----- WHEEL: $($wheelfile.Name) -----`n" | Tee-Object -FilePath 'diagnostics.txt' -Append
          $destdir = New-Item -Path $baseextract.FullName -Name $wheelfile.Basename -ItemType 'directory'
          Expand-Archive -Path $wheelfile.FullName -DestinationPath $destdir.FullName
          dumpbin /exports /imports $((Get-ChildItem -Path $destdir.FullName -Filter '*.pyd' -Recurse).FullName) | Tee-Object -FilePath 'diagnostics.txt' -Append
          Write-Output "`n" | Tee-Object -FilePath 'diagnostics.txt' -Append
        }
    - name: Diagnostics (macOS)
      if: ${{ runner.os == 'macOS' }}
      continue-on-error: true
      run: |
        touch 'diagnostics.txt'
        for wheelfile in wheelhouse/adrt-*.whl; do
          if [[ ! -e "$wheelfile" ]]; then
            continue
          fi
          echo "----- WHEEL: $(basename $wheelfile) -----" | tee -a 'diagnostics.txt'
          dir="$(mktemp -d)"
          unzip -q "$wheelfile" -d "$dir"
          echo 'Libraries:' | tee -a 'diagnostics.txt'
          otool -L -arch all "${dir}"/adrt/*.so | tee -a 'diagnostics.txt'
          echo 'Symbols:' | tee -a 'diagnostics.txt'
          nm -arch all "${dir}"/adrt/*.so | tee -a 'diagnostics.txt'
          echo | tee -a 'diagnostics.txt'
        done
    - name: Prepare diagnostics upload
      continue-on-error: true
      run: mv 'diagnostics.txt' 'diagnostics-${{ runner.os }}-${{ runner.arch }}-run${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-job${{ github.job }}.txt'
    - name: Store diagnostics
      uses: actions/upload-artifact@v3
      with:
        name: diagnostics
        path: diagnostics-*.txt
        if-no-files-found: warn
  check-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [sdist, wheel]
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      id: setup-python
      with:
        python-version: '3.10'
    - name: Cache pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-releasecheckartifacts-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: |
          pip-releasecheckartifacts-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
          pip-releasecheck-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
          pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine
    - name: Download sdist
      uses: actions/download-artifact@v3
      with:
        name: sdist
        path: dist/
    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: dist/
    - name: Check artifacts
      run: python -m twine check --strict dist/*
  test-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: wheel
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v3
      id: setup-python
      with:
        python-version: ${{ matrix.python }}
    - name: Cache pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-releasetest-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: |
          pip-releasetest-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
          pip-releasecheck-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
          pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox
    - name: Download wheel
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: dist/
    - name: Run tox tests
      run: python -m tox -e py --installpkg dist/adrt-*-manylinux*_x86_64.whl
    - name: Clean up
      run: python -m pip cache remove adrt || true
  test-manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    timeout-minutes: 20
    needs: wheel
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Download wheel
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: dist/
    - name: Run tox tests
      run: pipx run tox -e py38,py39,py310 --installpkg dist/adrt-*-manylinux*_x86_64.whl
  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [check-artifacts, test-ubuntu, test-manylinux]
    permissions:
      contents: write
    steps:
    - name: Download sdist
      uses: actions/download-artifact@v3
      with:
        name: sdist
        path: dist/
    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: dist/
    - name: Compute checksums
      run: |
        echo -e '<details><summary>SHA256 Checksums</summary>\n\n```' | tee 'release_body.md'
        sha256sum dist/adrt-*.tar.gz dist/adrt-*.whl | sed 's!dist/!!' | tee -a 'release_body.md'
        echo -e '```\n\n</details>' | tee -a 'release_body.md'
    - name: Create release
      run: |
        gh release create '${{ github.ref_name }}' --target '${{ github.sha }}' --draft --notes-file 'release_body.md' --repo '${{ github.repository }}' dist/adrt-*.tar.gz dist/adrt-*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download diagnostics
      uses: actions/download-artifact@v3
      with:
        name: diagnostics
        path: diagnostics/
    - name: Show archive contents
      run: |
        for f in dist/*.tar.gz; do
          echo "----- FILE: $(basename $f) -----"
          tar -tzvf "$f"
          echo
        done
        for f in dist/*.whl; do
          echo "----- FILE: $(basename $f) -----"
          zipinfo "$f"
          echo
        done
    - name: Show diagnostics
      run: cat diagnostics/*.txt
