name: "Tests"
on:
  pull_request:
  push:
    branches:
      - '*'
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: '3.9'
    - name: Cache pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-lint-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: pip-lint-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox
    - name: Run linters
      run: tox -e lint,checkver
    - name: Clean up
      run: python -m pip cache remove adrt || true
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
        include:
          - python: '3.9'
            cflags: '-fopenmp'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: ${{ matrix.python }}
    - name: Cache pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox
    - name: Run tox tests
      run: tox -e py
      env:
        CFLAGS: ${{ matrix.cflags }}
    - name: Clean up
      run: python -m pip cache remove adrt || true
