name: "Tests"
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install linters
      run: pip install --upgrade flake8 pep8-naming flake8-bugbear
    - name: Lint with flake8
      run: flake8 adrt/ tests/ setup.py
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install tox
      run: pip install --upgrade tox
    - name: Run tox tests
      run: tox -e py
